version: "3.8"

services:
    db:
        image: mysql:8.0
        command: --default-authentication-plugin=caching_sha2_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "${MYSQL_PORT}:3306"
        volumes:
            - ./db:/var/lib/mysql
    api:
        build:
            context: ./api
            dockerfile: Dockerfile
        environment:
            DATABASE_URL: mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
        depends_on:
            - db
        ports:
            - "5000:5000"
